"""adicionado campo de update/modificacao

Revision ID: a1db287ce2df
Revises: 31369704d778
Create Date: 2023-04-03 22:14:00.192721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1db287ce2df'
down_revision = '31369704d778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_mod', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_column('date_mod')

    # ### end Alembic commands ###
